language: java
sudo: false
cache:
  directories:
    - "$HOME/.m2"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 
  - "rest/target/rest-*.war"
  - "collector/target/KubernetesDataCollector-*-jar-with-dependencies.jar"
  skip_cleanup: true
  on:
    tags: true
